theme: jekyll-theme-chirpy

baseurl: ''

lang: en

timezone: Asia/Jakarta

title: root

tagline: The future belongs to those who prepare for today 

description: >-

url: 'https://blog.linuxhacking.ac.id'

github:
  username:

twitter:
  username: idsec_

social:

  name: Enogembok
  email: eno@itsec.ac.id
  links:
    - https://twitter.com/Enogembok
    - https://github.com/
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification:

# ↑ --------------------------


google_analytics:
  id: 'G-CF9VBBH1LK'
  pv:
    proxy_endpoint:
    cache_path:

theme_mode:

img_cdn: ''

avatar: '/assets/img/favicons/avatar.jpg'

toc: true

valine:
  comments: true
  leancloud_appid: FWkEX16hdTMRmYzFQeIqS4GH-MdYXbMMI
  leancloud_appkey: ihjgIDYfMOWOfiX7hkrQrGXR
  placeholder: Your Comments.
  avatar: wavatar

paginate: 7

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      autoads: true
      permalink: /:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
